# Convolutional Neural Network
## Feature Extraction

This is about the operation of Convolutional layer in CNN. We have two filters (filter-1 and filter-2) as below.

In [115]:
import numpy as np
import pandas as pd

class CNN:
    def __init__(self, input = None, filters = None, biases = None, stride = 1):
        self.input = np.array(input)
        self.filters = np.array(filters)
        self.biases = np.array(biases)
        self.stride = stride
        self.output = np.array(None)

    def set_input(self, input: list):
        self.input = np.array(input)

    def add_filter(self, filter, bias):
        self.filters

    def __str__(self) -> str:
        return f"input:\n{self.input}\n\nfilters:\n{self.filters}\n\nbiases: {self.biases}\n\nstride: {self.stride}\n"

    @staticmethod
    def output_size(input_size: int, filter_size: int, stride: int) -> int:
        return int(1+(input_size-filter_size)/stride)

    def output_shape(self):
        return (self.filters.shape[0], self.output_size(self.input.shape[1], self.filters.shape[2], self.stride), self.output_size(self.input.shape[2], self.filters.shape[3], self.stride))

    def computation(self, input_section, filter, bias):
        mult_list = []
        nl, nr, nc = input_section.shape
        for l in range(nl):
            for r in range(nr):
                for c in range(nc):
                    mult_list.append(f'{input_section[l][r][c]}*{filter[l][r][c]}')
            mult_list.append(f'{bias}')
        return ' + '.join(mult_list)

    def convolution(self, print_computation = False):
        self.output = np.zeros(self.output_shape())
        x, y, z = 2, 1, 0
        for o_l in range(self.output.shape[z]):
            filter = self.filters[o_l]
            bias = biases[o_l]
            r = 0
            for o_r in range(self.output.shape[y]):
                c = 0
                if print_computation: print(f'Calculations of Output Layer {o_l} row {o_r}:')
                for o_c in range(self.output.shape[x]):
                    input_section = self.input[:, r:r+filter.shape[y], c:c+filter.shape[x]]
                    c += self.stride
                    self.output[o_l][o_r][o_c] = np.sum(input_section * filter) + bias
                    if print_computation: print(f"\tOutput[{o_l},{o_r},{o_c}] = {self.computation(input_section, filter, bias)} = {self.output[o_l][o_r][o_c]}")
                if print_computation: print(f'\n\tUpdated Output Layer {o_l}: \n{self.output[o_l]}\n\n')
                r += self.stride
        print(f'Final Output Layers:\n{self.output}\n\n')
        # df = pd.DataFrame(layer)
        # html = df.to_html()
        # print(html)

We have four gray scale images (a, b, c, and d), typically zero is taken to be black, and 255 is
taken to be white. We want to apply two filters (Filter-1 and Filter-2) for each image. Show the
output volumes of each input image along with the computation process.

In [116]:
inputs = np.array([
    [[
        [80,  90,  100,  0,  0,  0,  0],
        [80,  90,  100,  0,  0,  0,  0],
        [80,  90,  100,  0,  0,  0,  0],
        [80,  90,  100,  0,  0,  0,  0],
        [80,  90,  100,  0,  0,  0,  0],
        [80,  90,  100,  0,  0,  0,  0],
        [80,  90,  100,  0,  0,  0,  0]
    ]],

    [[
        [0,  0,  0,  0,  255,  255,  0],
        [0,  0,  0,  0,  190,  200,  0],
        [0,  0,  0,  0,  255,  255,  0],
        [0,  0,  0,  0,  100,  100,  0],
        [0,  0,  0,  0,  255,  255,  0],
        [0,  0,  0,  0,  255,  255,  0],
        [0,  0,  0,  0,  255,  255,  0]
    ]],

    [[
        [0,  0,  0,  0,  0,  0,  0],
        [0,  100,  110,  100,  90,  120,  0],
        [0,  0,  0,  0,  110,  0,  0],
        [0,  0,  0,  100,  0,  0,  0],
        [0,  0,  90,  0,  0,  0,  0],
        [0,  110,  90,  100,  100,  110,  0],
        [0,  0,  0,  0,  0,  0,  0]
    ]],

    [[
        [0,  0,  0,  0,  0,  0,  0],
        [0,  0,  0,  0,  0,  0,  0],
        [100,  110,  110,  90,  110,  120,  0],
        [0,  0,  0,  0,  0,  120,  0],
        [0,  110,  110,  90,  100,  110,  0],
        [0,  110,  0,  0,  0,  0,  0],
        [0,  110,  90,  100,  100,  100,  0]
    ]]
])
print(inputs.shape)

(4, 1, 7, 7)


In [117]:
for input in inputs:
    cnn = CNN(
        input = input,
        filters = [
            [
                [
                    [1, 1, 1], 
                    [0, 0, 0], 
                    [-1, -1, -1]
                ]
            ],
            [
                [
                    [1, 0, -1], 
                    [1, 0, -1], 
                    [1, 0, -1]
                ]
            ]
        ],
        biases = [0,  0],
        stride = 1
    )
    print(cnn)
    cnn.convolution(print_computation = False)

input:
[[[ 80  90 100   0   0   0   0]
  [ 80  90 100   0   0   0   0]
  [ 80  90 100   0   0   0   0]
  [ 80  90 100   0   0   0   0]
  [ 80  90 100   0   0   0   0]
  [ 80  90 100   0   0   0   0]
  [ 80  90 100   0   0   0   0]]]

filters:
[[[[ 1  1  1]
   [ 0  0  0]
   [-1 -1 -1]]]


 [[[ 1  0 -1]
   [ 1  0 -1]
   [ 1  0 -1]]]]

biases: [0 0]

stride: 1

Final Output Layers:
[[[  0.   0.   0.   0.   0.]
  [  0.   0.   0.   0.   0.]
  [  0.   0.   0.   0.   0.]
  [  0.   0.   0.   0.   0.]
  [  0.   0.   0.   0.   0.]]

 [[-60. 270. 300.   0.   0.]
  [-60. 270. 300.   0.   0.]
  [-60. 270. 300.   0.   0.]
  [-60. 270. 300.   0.   0.]
  [-60. 270. 300.   0.   0.]]]


input:
[[[  0   0   0   0 255 255   0]
  [  0   0   0   0 190 200   0]
  [  0   0   0   0 255 255   0]
  [  0   0   0   0 100 100   0]
  [  0   0   0   0 255 255   0]
  [  0   0   0   0 255 255   0]
  [  0   0   0   0 255 255   0]]]

filters:
[[[[ 1  1  1]
   [ 0  0  0]
   [-1 -1 -1]]]


 [[[ 1  0 -1]
   [ 1  0 -1]
   [ 

In [118]:
cnn = CNN(
    input = [
        [
            [80,  90,  100,  0,  0,  0,  0],
            [80,  90,  100,  0,  0,  0,  0],
            [80,  90,  100,  0,  0,  0,  0],
            [80,  90,  100,  0,  0,  0,  0],
            [80,  90,  100,  0,  0,  0,  0],
            [80,  90,  100,  0,  0,  0,  0],
            [80,  90,  100,  0,  0,  0,  0]
        ]
    ],
    filters = [
        [
            [
                [1, 1, 1], 
                [0, 0, 0], 
                [-1, -1, -1]
            ]
        ],
        [
            [
                [1, 0, -1], 
                [1, 0, -1], 
                [1, 0, -1]
            ]
        ]
    ],
    biases = [0,  0],
    stride = 1
)
print(cnn.output_shape())
cnn.convolution(print_computation = True)

(2, 5, 5)
Calculations of Output Layer 0 row 0:
	Output[0,0,0] = 80*1 + 90*1 + 100*1 + 80*0 + 90*0 + 100*0 + 80*-1 + 90*-1 + 100*-1 + 0 = 0.0
	Output[0,0,1] = 90*1 + 100*1 + 0*1 + 90*0 + 100*0 + 0*0 + 90*-1 + 100*-1 + 0*-1 + 0 = 0.0
	Output[0,0,2] = 100*1 + 0*1 + 0*1 + 100*0 + 0*0 + 0*0 + 100*-1 + 0*-1 + 0*-1 + 0 = 0.0
	Output[0,0,3] = 0*1 + 0*1 + 0*1 + 0*0 + 0*0 + 0*0 + 0*-1 + 0*-1 + 0*-1 + 0 = 0.0
	Output[0,0,4] = 0*1 + 0*1 + 0*1 + 0*0 + 0*0 + 0*0 + 0*-1 + 0*-1 + 0*-1 + 0 = 0.0

	Updated Output Layer 0: 
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


Calculations of Output Layer 0 row 1:
	Output[0,1,0] = 80*1 + 90*1 + 100*1 + 80*0 + 90*0 + 100*0 + 80*-1 + 90*-1 + 100*-1 + 0 = 0.0
	Output[0,1,1] = 90*1 + 100*1 + 0*1 + 90*0 + 100*0 + 0*0 + 90*-1 + 100*-1 + 0*-1 + 0 = 0.0
	Output[0,1,2] = 100*1 + 0*1 + 0*1 + 100*0 + 0*0 + 0*0 + 100*-1 + 0*-1 + 0*-1 + 0 = 0.0
	Output[0,1,3] = 0*1 + 0*1 + 0*1 + 0*0 + 0*0 + 0*0 + 0*-1 + 0*-1 + 0*-1 + 0 = 0.0
	O